# Database Configuration - Informations about database location and credentials
database:
  host: 127.0.0.1
  port: 3306
  user: root
  password: root
  name: pinkflowers

# Website Configuration - name, theme and init state
website:
  name: pinkFlower
  theme: default
  initialized: false
