# Database Configuration - Informations about database location and credentials
database:
  host: localhost
  port: 3306
  user: root
  password: 159753
  name: pinkflowers

# Website Configuration - name, theme and init state
website:
  name: pinkFlower
  theme: default
  initialized: false
