home_page:
  path: /
  defaults: { _controller: 'App\Controllers\FrontController::homeAction' }
  methods: [GET]

post_page:
  path: /articles/{slug}
  defaults: { _controller: 'App\Controllers\FrontController::viewPostAction' }
  methods: [GET]

#### POSTS ROUTES ###

# POSTS #
create_post:
  path: /posts/create
  defaults: { _controller: 'App\Controllers\PostController::createAction'}
  methods:  [GET]

save_post:
  path: /posts/create
  defaults: { _controller: 'App\Controllers\PostController::saveAction'}
  methods:  [POST]

list_posts:
  path: /posts
  defaults: { _controller: 'App\Controllers\PostController::listAction' }
  methods: [GET]

view_post:
  path: /posts/{id}
  defaults: { _controller: 'App\Controllers\PostController::viewAction' }
  methods: [GET]

delete_post:
  path: /posts/{id}/delete
  defaults: { _controller: 'App\Controllers\PostController::deleteAction' }
  methods: [GET]

edit_post:
  path: /posts/{id}/edit
  defaults: { _controller: 'App\Controllers\PostController::editAction' }
  methods: [GET]

update_post:
  path: /posts/{id}/edit
  defaults: { _controller: 'App\Controllers\PostController::updateAction' }
  methods: [POST]

#### CATEGORIES ROUTES ####

list_categories:
  path: /categories
  defaults: { _controller: 'App\Controllers\CategoryController::listAction' }
  methods: [GET]

create_category:
  path: /categories/create
  defaults: { _controller: 'App\Controllers\CategoryController::createAction' }
  methods: [GET]

save_category:
  path: /categories/create
  defaults: { _controller: 'App\Controllers\CategoryController::saveAction' }
  methods: [POST]

edit_category:
  path: /categories/{id}/edit
  defaults: { _controller: 'App\Controllers\CategoryController::editAction' }
  methods: [GET]

update_category:
  path: /categories/{id}/edit
  defaults: { _controller: 'App\Controllers\CategoryController::updateAction' }
  methods: [POST]

delete_cateogry:
  path: /categories/{id}/delete
  defaults: { _controller: 'App\Controllers\CategoryController::deleteAction' }
  methods: [GET]

view_category:
  path: /categories/{id}
  defaults: { _controller: 'App\Controllers\CategoryController::viewAction' }
  methods: [GET]

#### PAGES ROUTES ###

list_pages:
  path: /pages
  defaults: { _controller: 'App\Controllers\PageController::listAction' }
  methods: [GET]

#### ACCOUNT ROUTES ###

# CONNEXION #
login:
  path: /login
  defaults: { _controller: 'App\Controllers\AuthController::loginAction'}
  methods:  [GET]

getUser:
  path: /login
  defaults: { _controller: 'App\Controllers\AuthController::getAccount'}
  methods:  [POST]

# INSCRIPTION #
create_user:
  path: /register
  defaults: { _controller: 'App\Controllers\AuthController::registerAction'}
  methods: [GET]
