hello_custom:
  path: /hello/{name}
  defaults: { _controller: 'App\Controllers\HelloController::helloCustomAction' }

hello:
  path: /hello
  defaults: { _controller: 'App\Controllers\HelloController::helloAction' }

test:
  path: /test
  defaults: { _controller: 'App\Controllers\HelloController::helloAction'}
