hello_custom:
  path: /hello/{name}
  defaults: { _controller: 'App\Controllers\HelloController::helloCustomAction' }

hello:
  path: /hello
  defaults: { _controller: 'App\Controllers\HelloController::helloAction' }

test:
  path: /test
  defaults: { _controller: 'App\Controllers\HelloController::helloAction'}

#### POSTS ROUTES ###

# POSTS #
create_post:
  path: /posts/create
  defaults: { _controller: 'App\Controllers\PostController::createAction'}
  methods:  [GET]

save_post:
  path: /posts/create
  defaults: { _controller: 'App\Controllers\PostController::saveAction'}
  methods:  [POST]

list_posts:
  path: /posts
  defaults: { _controller: 'App\Controllers\PostController::listAction' }
  methods: [GET]

view_post:
  path: /posts/{id}
  defaults: { _controller: 'App\Controllers\PostController::viewAction' }
  methods: [GET]

delete_post:
  path: /posts/{id}/delete
  defaults: { _controller: 'App\Controllers\PostController::deleteAction' }
  methods: [GET]

edit_post:
  path: /posts/{id}/edit
  defaults: { _controller: 'App\Controllers\PostController::editAction' }
  methods: [GET]

update_post:
  path: /posts/{id}/edit
  defaults: { _controller: 'App\Controllers\PostController::updateAction' }
  methods: [POST]

#### CATEGORIES ROUTES ####

create_category:
  path: /categories/create
  defaults: { _controller: 'App\Controllers\CategoryController::createAction' }
  methods: [GET]

save_category:
  path: /categories/create
  defaults: { _controller: 'App\Controllers\CategoryController::saveAction' }
  methods: [POST]

edit_category:
  path: /categories/{id}/edit
  defaults: { _controller: 'App\Controllers\CategoryController::editAction' }
  methods: [GET]

update_category:
  path: /categories/{id}/edit
  defaults: { _controller: 'App\Controllers\CategoryController::updateAction' }
  methods: [POST]

#### ACCOUNT ROUTES ###

# CONNEXION #
login:
  path: /login
  defaults: { _controller: 'App\Controllers\AuthController::loginAction'}
  methods:  [GET]

getUser:
  path: /login
  defaults: { _controller: 'App\Controllers\AuthController::getAccount'}
  methods:  [POST]

# INSCRIPTION #
create_user:
  path: /register
  defaults: { _controller: 'App\Controllers\AuthController::registerAction'}
  methods: [GET]
